import { authRoles } from 'app/auth';
import i18next from 'i18next';
import DocumentationNavigation from '../main/documentation/DocumentationNavigation';

import ar from './navigation-i18n/ar';
import en from './navigation-i18n/en';
import tr from './navigation-i18n/tr';

i18next.addResourceBundle('en', 'navigation', en);
i18next.addResourceBundle('tr', 'navigation', tr);
i18next.addResourceBundle('ar', 'navigation', ar);

const navigationConfig = [
  {
    id: 'dashboards',
    title: 'Dashboards',
    subtitle: 'Unique dashboard designs',
    type: 'group',
    icon: 'heroicons-outline:home',
    children: [
      {
        id: 'dashboards.project',
        title: 'Project',
        type: 'item',
        icon: 'heroicons-outline:clipboard-check',
        url: '/dashboards/project',
      },
      {
        id: 'dashboards.analytics',
        title: 'Analytics',
        type: 'item',
        icon: 'heroicons-outline:chart-pie',
        url: '/dashboards/analytics',
      },
    ],
  },

  {
    id: 'apps',
    title: 'Applications',
    subtitle: 'Custom made application designs',
    type: 'group',
    icon: 'heroicons-outline:home',
    children: [
      {
        id: 'apps.academy',
        title: 'Academy',
        type: 'item',
        icon: 'heroicons-outline:academic-cap',
        url: '/apps/academy',
      },
      {
        id: 'apps.calendar',
        title: 'Calendar',
        subtitle: '3 upcoming events',
        type: 'item',
        icon: 'heroicons-outline:calendar',
        url: '/apps/calendar',
      },
      {
        id: 'apps.chat',
        title: 'Chat',
        type: 'item',
        icon: 'heroicons-outline:chat-alt',
        url: '/apps/chat',
      },
      {
        id: 'apps.contacts',
        title: 'Contacts',
        type: 'item',
        icon: 'heroicons-outline:user-group',
        url: '/apps/contacts',
      },
      {
        id: 'apps.ecommerce',
        title: 'ECommerce',
        type: 'collapse',
        icon: 'heroicons-outline:shopping-cart',
        children: [
          {
            id: 'e-commerce-products',
            title: 'Products',
            type: 'item',
            url: 'apps/e-commerce/products',
            end: true,
          },
          {
            id: 'e-commerce-product-detail',
            title: 'Product Detail',
            type: 'item',
            url: 'apps/e-commerce/products/1/a-walk-amongst-friends-canvas-print',
          },
          {
            id: 'e-commerce-new-product',
            title: 'New Product',
            type: 'item',
            url: 'apps/e-commerce/products/new',
          },
          {
            id: 'e-commerce-orders',
            title: 'Orders',
            type: 'item',
            url: 'apps/e-commerce/orders',
            end: true,
          },
          {
            id: 'e-commerce-order-detail',
            title: 'Order Detail',
            type: 'item',
            url: 'apps/e-commerce/orders/1',
          },
        ],
      },
      {
        id: 'apps.file-manager',
        title: 'File Manager',
        type: 'item',
        icon: 'heroicons-outline:cloud',
        url: '/apps/file-manager',
        end: true,
      },
      {
        id: 'apps.help-center',
        title: 'Help Center',
        type: 'collapse',
        icon: 'heroicons-outline:support',
        url: '/apps/help-center',
        children: [
          {
            id: 'apps.help-center.home',
            title: 'Home',
            type: 'item',
            url: '/apps/help-center',
            end: true,
          },
          {
            id: 'apps.help-center.faqs',
            title: 'FAQs',
            type: 'item',
            url: '/apps/help-center/faqs',
          },
          {
            id: 'apps.help-center.guides',
            title: 'Guides',
            type: 'item',
            url: '/apps/help-center/guides',
          },
          {
            id: 'apps.help-center.support',
            title: 'Support',
            type: 'item',
            url: '/apps/help-center/support',
          },
        ],
      },
      {
        id: 'apps.mailbox',
        title: 'Mailbox',
        type: 'item',
        icon: 'heroicons-outline:mail',
        url: '/apps/mailbox',
        badge: {
          title: '27',
          classes: 'px-2 bg-pink-600 text-white rounded-full',
        },
      },
      {
        id: 'apps.notes',
        title: 'Notes',
        type: 'item',
        icon: 'heroicons-outline:pencil-alt',
        url: '/apps/notes',
      },
      {
        id: 'apps.scrumboard',
        title: 'Scrumboard',
        type: 'item',
        icon: 'heroicons-outline:view-boards',
        url: '/apps/scrumboard',
      },
      {
        id: 'apps.tasks',
        title: 'Tasks',
        subtitle: '12 remaining tasks',
        type: 'item',
        icon: 'heroicons-outline:check-circle',
        url: '/apps/tasks',
      },
    ],
  },
  {
    id: 'pages',
    title: 'Pages',
    subtitle: 'Custom made page designs',
    type: 'group',
    icon: 'heroicons-outline:document',
    children: [
      {
        id: 'pages.activities',
        title: 'Activities',
        type: 'item',
        icon: 'heroicons-outline:menu-alt-2',
        url: '/pages/activities',
      },
      {
        id: 'pages.authentication',
        title: 'Authentication',
        type: 'collapse',
        icon: 'heroicons-outline:lock-closed',
        children: [
          {
            id: 'pages.authentication.sign-in',
            title: 'Sign in',
            type: 'collapse',
            children: [
              {
                id: 'pages.authentication.sign-in.classic',
                title: 'Classic',
                type: 'item',
                url: '/pages/authentication/sign-in/classic',
              },
              {
                id: 'pages.authentication.sign-in.modern',
                title: 'Modern',
                type: 'item',
                url: '/pages/authentication/sign-in/modern',
              },
              {
                id: 'pages.authentication.sign-in.modern-reversed',
                title: 'Modern Reversed',
                type: 'item',
                url: '/pages/authentication/sign-in/modern-reversed',
              },
              {
                id: 'pages.authentication.sign-in.split-screen',
                title: 'Split Screen',
                type: 'item',
                url: '/pages/authentication/sign-in/split-screen',
              },
              {
                id: 'pages.authentication.sign-in.split-screen-reversed',
                title: 'Split Screen Reversed',
                type: 'item',
                url: '/pages/authentication/sign-in/split-screen-reversed',
              },
              {
                id: 'pages.authentication.sign-in.full-screen',
                title: 'Full Screen',
                type: 'item',
                url: '/pages/authentication/sign-in/full-screen',
              },
              {
                id: 'pages.authentication.sign-in.full-screen-reversed',
                title: 'Full Screen Reversed',
                type: 'item',
                url: '/pages/authentication/sign-in/full-screen-reversed',
              },
            ],
          },
          {
            id: 'pages.authentication.sign-up',
            title: 'Sign up',
            type: 'collapse',
            children: [
              {
                id: 'pages.authentication.sign-up.classic',
                title: 'Classic',
                type: 'item',
                url: '/pages/authentication/sign-up/classic',
              },
              {
                id: 'pages.authentication.sign-up.modern',
                title: 'Modern',
                type: 'item',
                url: '/pages/authentication/sign-up/modern',
              },
              {
                id: 'pages.authentication.sign-up.modern-reversed',
                title: 'Modern Reversed',
                type: 'item',
                url: '/pages/authentication/sign-up/modern-reversed',
              },
              {
                id: 'pages.authentication.sign-up.split-screen',
                title: 'Split Screen',
                type: 'item',
                url: '/pages/authentication/sign-up/split-screen',
              },
              {
                id: 'pages.authentication.sign-up.split-screen-reversed',
                title: 'Split Screen Reversed',
                type: 'item',
                url: '/pages/authentication/sign-up/split-screen-reversed',
              },
              {
                id: 'pages.authentication.sign-up.full-screen',
                title: 'Full Screen',
                type: 'item',
                url: '/pages/authentication/sign-up/full-screen',
              },
              {
                id: 'pages.authentication.sign-up.full-screen-reversed',
                title: 'Full Screen Reversed',
                type: 'item',
                url: '/pages/authentication/sign-up/full-screen-reversed',
              },
            ],
          },
          {
            id: 'pages.authentication.sign-out',
            title: 'Sign out',
            type: 'collapse',
            children: [
              {
                id: 'pages.authentication.sign-out.classic',
                title: 'Classic',
                type: 'item',
                url: '/pages/authentication/sign-out/classic',
              },
              {
                id: 'pages.authentication.sign-out.modern',
                title: 'Modern',
                type: 'item',
                url: '/pages/authentication/sign-out/modern',
              },
              {
                id: 'pages.authentication.sign-out.modern-reversed',
                title: 'Modern Reversed',
                type: 'item',
                url: '/pages/authentication/sign-out/modern-reversed',
              },
              {
                id: 'pages.authentication.sign-out.split-screen',
                title: 'Split Screen',
                type: 'item',
                url: '/pages/authentication/sign-out/split-screen',
              },
              {
                id: 'pages.authentication.sign-out.split-screen-reversed',
                title: 'Split Screen Reversed',
                type: 'item',
                url: '/pages/authentication/sign-out/split-screen-reversed',
              },
              {
                id: 'pages.authentication.sign-out.full-screen',
                title: 'Full Screen',
                type: 'item',
                url: '/pages/authentication/sign-out/full-screen',
              },
              {
                id: 'pages.authentication.sign-out.full-screen-reversed',
                title: 'Full Screen Reversed',
                type: 'item',
                url: '/pages/authentication/sign-out/full-screen-reversed',
              },
            ],
          },
          {
            id: 'pages.authentication.forgot-password',
            title: 'Forgot password',
            type: 'collapse',
            children: [
              {
                id: 'pages.authentication.forgot-password.classic',
                title: 'Classic',
                type: 'item',
                url: '/pages/authentication/forgot-password/classic',
              },
              {
                id: 'pages.authentication.forgot-password.modern',
                title: 'Modern',
                type: 'item',
                url: '/pages/authentication/forgot-password/modern',
              },
              {
                id: 'pages.authentication.forgot-password.modern-reversed',
                title: 'Modern Reversed',
                type: 'item',
                url: '/pages/authentication/forgot-password/modern-reversed',
              },
              {
                id: 'pages.authentication.forgot-password.split-screen',
                title: 'Split Screen',
                type: 'item',
                url: '/pages/authentication/forgot-password/split-screen',
              },
              {
                id: 'pages.authentication.forgot-password.split-screen-reversed',
                title: 'Split Screen Reversed',
                type: 'item',
                url: '/pages/authentication/forgot-password/split-screen-reversed',
              },
              {
                id: 'pages.authentication.forgot-password.full-screen',
                title: 'Full Screen',
                type: 'item',
                url: '/pages/authentication/forgot-password/full-screen',
              },
              {
                id: 'pages.authentication.forgot-password.full-screen-reversed',
                title: 'Full Screen Reversed',
                type: 'item',
                url: '/pages/authentication/forgot-password/full-screen-reversed',
              },
            ],
          },
          {
            id: 'pages.authentication.reset-password',
            title: 'Reset password',
            type: 'collapse',
            children: [
              {
                id: 'pages.authentication.reset-password.classic',
                title: 'Classic',
                type: 'item',
                url: '/pages/authentication/reset-password/classic',
              },
              {
                id: 'pages.authentication.reset-password.modern',
                title: 'Modern',
                type: 'item',
                url: '/pages/authentication/reset-password/modern',
              },
              {
                id: 'pages.authentication.reset-password.modern-reversed',
                title: 'Modern Reversed',
                type: 'item',
                url: '/pages/authentication/reset-password/modern-reversed',
              },
              {
                id: 'pages.authentication.reset-password.split-screen',
                title: 'Split Screen',
                type: 'item',
                url: '/pages/authentication/reset-password/split-screen',
              },
              {
                id: 'pages.authentication.reset-password.split-screen-reversed',
                title: 'Split Screen Reversed',
                type: 'item',
                url: '/pages/authentication/reset-password/split-screen-reversed',
              },
              {
                id: 'pages.authentication.reset-password.full-screen',
                title: 'Full Screen',
                type: 'item',
                url: '/pages/authentication/reset-password/full-screen',
              },
              {
                id: 'pages.authentication.reset-password.full-screen-reversed',
                title: 'Full Screen Reversed',
                type: 'item',
                url: '/pages/authentication/reset-password/full-screen-reversed',
              },
            ],
          },
          {
            id: 'pages.authentication.unlock-session',
            title: 'Unlock session',
            type: 'collapse',
            children: [
              {
                id: 'pages.authentication.unlock-session.classic',
                title: 'Classic',
                type: 'item',
                url: '/pages/authentication/unlock-session/classic',
              },
              {
                id: 'pages.authentication.unlock-session.modern',
                title: 'Modern',
                type: 'item',
                url: '/pages/authentication/unlock-session/modern',
              },
              {
                id: 'pages.authentication.unlock-session.modern-reversed',
                title: 'Modern Reversed',
                type: 'item',
                url: '/pages/authentication/unlock-session/modern-reversed',
              },
              {
                id: 'pages.authentication.unlock-session.split-screen',
                title: 'Split Screen',
                type: 'item',
                url: '/pages/authentication/unlock-session/split-screen',
              },
              {
                id: 'pages.authentication.unlock-session.split-screen-reversed',
                title: 'Split Screen Reversed',
                type: 'item',
                url: '/pages/authentication/unlock-session/split-screen-reversed',
              },
              {
                id: 'pages.authentication.unlock-session.full-screen',
                title: 'Full Screen',
                type: 'item',
                url: '/pages/authentication/unlock-session/full-screen',
              },
              {
                id: 'pages.authentication.unlock-session.full-screen-reversed',
                title: 'Full Screen Reversed',
                type: 'item',
                url: '/pages/authentication/unlock-session/full-screen-reversed',
              },
            ],
          },
          {
            id: 'pages.authentication.confirmation-required',
            title: 'Confirmation required',
            type: 'collapse',
            children: [
              {
                id: 'pages.authentication.confirmation-required.classic',
                title: 'Classic',
                type: 'item',
                url: '/pages/authentication/confirmation-required/classic',
              },
              {
                id: 'pages.authentication.confirmation-required.modern',
                title: 'Modern',
                type: 'item',
                url: '/pages/authentication/confirmation-required/modern',
              },
              {
                id: 'pages.authentication.confirmation-required.modern-reversed',
                title: 'Modern Reversed',
                type: 'item',
                url: '/pages/authentication/confirmation-required/modern-reversed',
              },
              {
                id: 'pages.authentication.confirmation-required.split-screen',
                title: 'Split Screen',
                type: 'item',
                url: '/pages/authentication/confirmation-required/split-screen',
              },
              {
                id: 'pages.authentication.confirmation-required.split-screen-reversed',
                title: 'Split Screen Reversed',
                type: 'item',
                url: '/pages/authentication/confirmation-required/split-screen-reversed',
              },
              {
                id: 'pages.authentication.confirmation-required.full-screen',
                title: 'Full Screen',
                type: 'item',
                url: '/pages/authentication/confirmation-required/full-screen',
              },
              {
                id: 'pages.authentication.confirmation-required.full-screen-reversed',
                title: 'Full Screen Reversed',
                type: 'item',
                url: '/pages/authentication/confirmation-required/full-screen-reversed',
              },
            ],
          },
        ],
      },
      {
        id: 'pages.coming-soon',
        title: 'Coming Soon',
        type: 'collapse',
        icon: 'heroicons-outline:clock',
        url: '/pages/coming-soon',
        children: [
          {
            id: 'pages.coming-soon.classic',
            title: 'Classic',
            type: 'item',
            url: '/pages/coming-soon/classic',
          },
          {
            id: 'pages.coming-soon.modern',
            title: 'Modern',
            type: 'item',
            url: '/pages/coming-soon/modern',
          },
          {
            id: 'pages.coming-soon.modern-reversed',
            title: 'Modern Reversed',
            type: 'item',
            url: '/pages/coming-soon/modern-reversed',
          },
          {
            id: 'pages.coming-soon.split-screen',
            title: 'Split Screen',
            type: 'item',
            url: '/pages/coming-soon/split-screen',
          },
          {
            id: 'pages.coming-soon.split-screen-reversed',
            title: 'Split Screen Reversed',
            type: 'item',
            url: '/pages/coming-soon/split-screen-reversed',
          },
          {
            id: 'pages.coming-soon.full-screen',
            title: 'Full Screen',
            type: 'item',
            url: '/pages/coming-soon/full-screen',
          },
          {
            id: 'pages.coming-soon.full-screen-reversed',
            title: 'Full Screen Reversed',
            type: 'item',
            url: '/pages/coming-soon/full-screen-reversed',
          },
        ],
      },
      {
        id: 'pages.error',
        title: 'Error',
        type: 'collapse',
        icon: 'heroicons-outline:exclamation-circle',
        children: [
          {
            id: 'pages.error.404',
            title: '404',
            type: 'item',
            url: '/pages/error/404',
          },
          {
            id: 'pages.error.500',
            title: '500',
            type: 'item',
            url: '/pages/error/500',
          },
        ],
      },
      {
        id: 'pages.invoice',
        title: 'Invoice',
        type: 'collapse',
        icon: 'heroicons-outline:calculator',
        children: [
          {
            id: 'pages.invoice.printable',
            title: 'Printable',
            type: 'collapse',
            children: [
              {
                id: 'pages.invoice.printable.compact',
                title: 'Compact',
                type: 'item',
                url: '/pages/invoice/printable/compact',
              },
              {
                id: 'pages.invoice.printable.modern',
                title: 'Modern',
                type: 'item',
                url: '/pages/invoice/printable/modern',
              },
            ],
          },
        ],
      },
      {
        id: 'pages.maintenance',
        title: 'Maintenance',
        type: 'item',
        icon: 'heroicons-outline:exclamation',
        url: '/pages/maintenance',
      },
      {
        id: 'pages.pricing',
        title: 'Pricing',
        type: 'collapse',
        icon: 'heroicons-outline:cash',
        children: [
          {
            id: 'pages.pricing.modern',
            title: 'Modern',
            type: 'item',
            url: '/pages/pricing/modern',
          },
          {
            id: 'pages.pricing.simple',
            title: 'Simple',
            type: 'item',
            url: '/pages/pricing/simple',
          },
          {
            id: 'pages.pricing.single',
            title: 'Single',
            type: 'item',
            url: '/pages/pricing/single',
          },
          {
            id: 'pages.pricing.table',
            title: 'Table',
            type: 'item',
            url: '/pages/pricing/table',
          },
        ],
      },
      {
        id: 'pages.profile',
        title: 'Profile',
        type: 'item',
        icon: 'heroicons-outline:user-circle',
        url: '/pages/profile',
      },
      {
        id: 'pages.settings',
        title: 'Settings',
        type: 'item',
        icon: 'heroicons-outline:cog',
        url: '/pages/settings',
      },
    ],
  },
  {
    id: 'user-interface',
    title: 'User Interface',
    subtitle: 'Building blocks of the UI & UX',
    type: 'group',
    icon: 'heroicons-outline:collection',
    children: [
      {
        id: 'user-interface.material-components',
        title: 'Material Components',
        type: 'item',
        icon: 'heroicons-outline:chip',
        url: '/ui/material-components',
      },
      {
        id: 'user-interface.fuse-components',
        title: 'Fuse Components',
        type: 'item',
        icon: 'heroicons-outline:chip',
        url: '/ui/fuse-components',
      },
      {
        id: 'user-interface.other-components',
        title: 'Other Components',
        type: 'item',
        icon: 'heroicons-outline:chip',
        url: '/ui/other-components',
      },
      {
        id: 'user-interface.tailwindcss',
        title: 'TailwindCSS',
        type: 'item',
        icon: 'heroicons-outline:sparkles',
        url: '/ui/tailwindcss',
      },
      {
        id: 'user-interface.advanced-search',
        title: 'Advanced Search',
        type: 'item',
        icon: 'heroicons-outline:search-circle',
        url: '/ui/advanced-search',
      },
      {
        id: 'user-interface.animations',
        title: 'Animations',
        type: 'item',
        icon: 'heroicons-outline:play',
        url: '/ui/animations',
      },
      {
        id: 'user-interface.cards',
        title: 'Cards',
        type: 'item',
        icon: 'heroicons-outline:duplicate',
        url: '/ui/cards',
      },
      {
        id: 'user-interface.colors',
        title: 'Colors',
        type: 'item',
        icon: 'heroicons-outline:color-swatch',
        url: '/ui/colors',
      },
      {
        id: 'user-interface.confirmation-dialog',
        title: 'Confirmation Dialog',
        type: 'item',
        icon: 'heroicons-outline:question-mark-circle',
        url: '/ui/confirmation-dialog',
      },
      {
        id: 'user-interface.datatable',
        title: 'Datatable',
        type: 'item',
        icon: 'heroicons-outline:view-list',
        url: '/ui/datatable',
      },
      {
        id: 'user-interface.forms',
        title: 'Forms',
        type: 'collapse',
        icon: 'heroicons-outline:pencil-alt',
        children: [
          {
            id: 'user-interface.forms.fields',
            title: 'Fields',
            type: 'item',
            url: '/ui/forms/fields',
          },
          {
            id: 'user-interface.forms.layouts',
            title: 'Layouts',
            type: 'item',
            url: '/ui/forms/layouts',
          },
          {
            id: 'user-interface.forms.wizards',
            title: 'Wizards',
            type: 'item',
            url: '/ui/forms/wizards',
          },
        ],
      },
      {
        id: 'user-interface.icons',
        title: 'Icons',
        type: 'collapse',
        icon: 'heroicons-outline:lightning-bolt',
        children: [
          {
            id: 'user-interface.icons.heroicons-outline',
            title: 'Heroicons Outline',
            type: 'item',
            url: '/ui/icons/heroicons-outline',
          },
          {
            id: 'user-interface.icons.heroicons-solid',
            title: 'Heroicons Solid',
            type: 'item',
            url: '/ui/icons/heroicons-solid',
          },
          {
            id: 'user-interface.icons.material-twotone',
            title: 'Material Twotone',
            type: 'item',
            url: '/ui/icons/material-twotone',
          },
          {
            id: 'user-interface.icons.material-outline',
            title: 'Material Outline',
            type: 'item',
            url: '/ui/icons/material-outline',
          },
          {
            id: 'user-interface.icons.material-solid',
            title: 'Material Solid',
            type: 'item',
            url: '/ui/icons/material-solid',
          },
          {
            id: 'user-interface.icons.iconsmind',
            title: 'Iconsmind',
            type: 'item',
            url: '/ui/icons/iconsmind',
          },
          {
            id: 'user-interface.icons.feather',
            title: 'Feather',
            type: 'item',
            url: '/ui/icons/feather',
          },
        ],
      },
      {
        id: 'user-interface.page-layouts',
        title: 'Page Layouts',
        type: 'collapse',
        icon: 'heroicons-outline:template',
        children: [
          {
            id: 'user-interface.page-layouts.overview',
            title: 'Overview',
            type: 'item',
            url: '/ui/page-layouts/overview',
          },
          {
            id: 'user-interface.page-layouts.empty',
            title: 'Empty',
            type: 'item',
            url: '/ui/page-layouts/empty',
          },
          {
            id: 'user-interface.page-layouts.carded',

            title: 'Carded',
            type: 'collapse',
            children: [
              {
                id: 'user-interface.page-layouts.carded.fullwidth',
                title: 'Fullwidth',
                type: 'item',
                url: '/ui/page-layouts/carded/fullwidth',
              },
              {
                id: 'user-interface.page-layouts.carded.left-sidebar-1',
                title: 'Left Sidebar #1',
                type: 'item',
                url: '/ui/page-layouts/carded/left-sidebar-1',
              },
              {
                id: 'user-interface.page-layouts.carded.left-sidebar-2',
                title: 'Left Sidebar #2',
                type: 'item',
                url: '/ui/page-layouts/carded/left-sidebar-2',
              },
              {
                id: 'user-interface.page-layouts.carded.right-sidebar-1',
                title: 'Right Sidebar #1',
                type: 'item',
                url: '/ui/page-layouts/carded/right-sidebar-1',
              },
              {
                id: 'user-interface.page-layouts.carded.right-sidebar-2',
                title: 'Right Sidebar #2',
                type: 'item',
                url: '/ui/page-layouts/carded/right-sidebar-2',
              },
            ],
          },
          {
            id: 'user-interface.page-layouts.simple',
            title: 'Simple',
            type: 'collapse',
            children: [
              {
                id: 'user-interface.page-layouts.simple.fullwidth-1',
                title: 'Fullwidth #1',
                type: 'item',
                url: '/ui/page-layouts/simple/fullwidth-1',
              },
              {
                id: 'user-interface.page-layouts.simple.fullwidth-2',
                title: 'Fullwidth #2',
                type: 'item',
                url: '/ui/page-layouts/simple/fullwidth-2',
              },
              {
                id: 'user-interface.page-layouts.simple.left-sidebar-1',
                title: 'Left Sidebar #1',
                type: 'item',
                url: '/ui/page-layouts/simple/left-sidebar-1',
              },
              {
                id: 'user-interface.page-layouts.simple.left-sidebar-2',
                title: 'Left Sidebar #2',
                type: 'item',
                url: '/ui/page-layouts/simple/left-sidebar-2',
              },
              {
                id: 'user-interface.page-layouts.simple.left-sidebar-3',
                title: 'Left Sidebar #3',
                type: 'item',
                url: '/ui/page-layouts/simple/left-sidebar-3',
              },
              {
                id: 'user-interface.page-layouts.simple.right-sidebar-1',
                title: 'Right Sidebar #1',
                type: 'item',
                url: '/ui/page-layouts/simple/right-sidebar-1',
              },
              {
                id: 'user-interface.page-layouts.simple.right-sidebar-2',
                title: 'Right Sidebar #2',
                type: 'item',
                url: '/ui/page-layouts/simple/right-sidebar-2',
              },
              {
                id: 'user-interface.page-layouts.simple.right-sidebar-3',
                title: 'Right Sidebar #3',
                type: 'item',
                url: '/ui/page-layouts/simple/right-sidebar-3',
              },
            ],
          },
        ],
      },
      {
        id: 'user-interface.typography',
        title: 'Typography',
        type: 'item',
        icon: 'heroicons-outline:pencil',
        url: '/ui/typography',
      },
    ],
  },
  {
    id: 'divider-1',
    type: 'divider',
  },
  {
    id: 'documentation',
    title: 'Documentation',
    subtitle: 'Everything you need to know about Fuse',
    type: 'group',
    icon: 'heroicons-outline:support',
    children: [
      {
        id: 'documentation.changelog',
        title: 'Changelog',
        type: 'item',
        icon: 'heroicons-outline:speakerphone',
        url: '/docs/changelog',
        badge: {
          title: '14.1.1',
          classes: 'px-2 bg-yellow-300 text-black rounded-full',
        },
      },
      {
        id: 'documentation.guides',
        title: 'Guides',
        type: 'item',
        icon: 'heroicons-outline:book-open',
        url: '/docs/guides',
      },
    ],
  },
  {
    id: 'divider-2',
    type: 'divider',
  },
  {
    id: 'navigation-features',
    title: 'Navigation features',
    subtitle: 'Collapsable levels & badge styles',
    type: 'group',
    icon: 'heroicons-outline:menu',
    children: [
      {
        id: 'navigation-features.level.0',
        title: 'Level 0',
        icon: 'heroicons-outline:check-circle',
        type: 'collapse',
        children: [
          {
            id: 'navigation-features.level.0.1',
            title: 'Level 1',
            type: 'collapse',
            children: [
              {
                id: 'navigation-features.level.0.1.2',
                title: 'Level 2',
                type: 'collapse',
                children: [
                  {
                    id: 'navigation-features.level.0.1.2.3',
                    title: 'Level 3',
                    type: 'collapse',
                    children: [
                      {
                        id: 'navigation-features.level.0.1.2.3.4',
                        title: 'Level 4',
                        type: 'collapse',
                        children: [
                          {
                            id: 'navigation-features.level.0.1.2.3.4.5',
                            title: 'Level 5',
                            type: 'collapse',
                            children: [
                              {
                                id: 'navigation-features.level.0.1.2.3.4.5.6',
                                title: 'Level 6',
                                type: 'item',
                              },
                            ],
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: 'navigation-features2.level.0',
        title: 'Level 0',
        subtitle: 'With subtitle',
        icon: 'heroicons-outline:check-circle',
        type: 'collapse',
        children: [
          {
            id: 'navigation-features2.level.0.1-1',
            title: 'Level 1.1',
            type: 'item',
          },
          {
            id: 'navigation-features2.level.0.1-2',
            title: 'Level 1.2',
            type: 'item',
          },
        ],
      },
      {
        id: 'navigation-features.active',
        title: 'Active item',
        subtitle: 'Manually marked as active',
        icon: 'heroicons-outline:check-circle',
        type: 'item',
        active: true,
      },
      {
        id: 'navigation-features.disabled-collapse',
        title: 'Disabled collapse',
        subtitle: 'Some subtitle',
        icon: 'heroicons-outline:check-circle',
        type: 'collapse',
        disabled: true,
        children: [
          {
            id: 'navigation-features.disabled-collapse.child',
            title: "You shouldn't be able to see this child",
            type: 'item',
          },
        ],
      },
      {
        id: 'navigation-features.disabled-item',
        title: 'Disabled item',
        subtitle: 'Some subtitle',
        icon: 'heroicons-outline:check-circle',
        type: 'item',
        disabled: true,
      },
      {
        id: 'navigation-features.badge-style-oval',
        title: 'Oval badge',
        icon: 'heroicons-outline:tag',
        type: 'item',
        badge: {
          title: '8',
          classes: 'w-5 h-5 bg-teal-400 text-black rounded-full',
        },
      },
      {
        id: 'navigation-features.badge-style-rectangle',
        title: 'Rectangle badge',
        icon: 'heroicons-outline:tag',
        type: 'item',
        badge: {
          title: 'Updated!',
          classes: 'px-2 bg-teal-400 text-black rounded',
        },
      },
      {
        id: 'navigation-features.badge-style-rounded',
        title: 'Rounded badge',
        icon: 'heroicons-outline:tag',
        type: 'item',
        badge: {
          title: 'NEW',
          classes: 'px-2.5 bg-teal-400 text-black rounded-full',
        },
      },
      {
        id: 'navigation-features.badge-style-simple',
        title: 'Simple badge',
        icon: 'heroicons-outline:tag',
        type: 'item',
        badge: {
          title: '87 Unread',
          classes: 'text-teal-500',
        },
      },
      {
        id: 'navigation-features.multi-line',
        title: 'A multi line navigation item title example which works just fine',
        icon: 'heroicons-outline:check-circle',
        type: 'item',
      },
    ],
  },
  {
    id: 'applications',
    title: 'Applications',
    translate: 'APPLICATIONS',
    type: 'group',
    icon: 'apps',
    children: [
      {
        id: 'dashboards',
        title: 'Dashboards',
        translate: 'DASHBOARDS',
        type: 'collapse',
        icon: 'dashboard',
        children: [
          {
            id: 'analytics-dashboard',
            title: 'Analytics',
            type: 'item',
            url: 'apps/dashboards/analytics',
          },
          {
            id: 'project-dashboard',
            title: 'Project',
            type: 'item',
            url: 'apps/dashboards/project',
          },
        ],
      },
      {
        id: 'calendar',
        title: 'Calendar',
        translate: 'CALENDAR',
        type: 'item',
        icon: 'today',
        url: 'apps/calendar',
      },
      {
        id: '1',
        title: 'E-Commerce',
        translate: 'ECOMMERCE',
        type: 'collapse',
        icon: 'shopping_cart',
        url: 'apps/e-commerce',
        children: [
          {
            id: 'e-commerce-products',
            title: 'Products',
            type: 'item',
            url: 'apps/e-commerce/products',
            end: true,
          },
          {
            id: 'e-commerce-product-detail',
            title: 'Product Detail',
            type: 'item',
            url: 'apps/e-commerce/products/1/a-walk-amongst-friends-canvas-print',
          },
          {
            id: 'e-commerce-new-product',
            title: 'New Product',
            type: 'item',
            url: 'apps/e-commerce/products/new',
          },
          {
            id: 'e-commerce-orders',
            title: 'Orders',
            type: 'item',
            url: 'apps/e-commerce/orders',
            end: true,
          },
          {
            id: 'e-commerce-order-detail',
            title: 'Order Detail',
            type: 'item',
            url: 'apps/e-commerce/orders/1',
          },
        ],
      },
      {
        id: 'academy',
        title: 'Academy',
        translate: 'ACADEMY',
        type: 'item',
        icon: 'school',
        url: 'apps/academy',
      },
      {
        id: 'mail',
        title: 'Mail',
        translate: 'MAIL',
        type: 'item',
        icon: 'email',
        url: 'apps/mail',
        badge: {
          title: 25,
          bg: '#F44336',
          fg: '#FFFFFF',
        },
      },
      {
        id: 'todo',
        title: 'To-Do',
        translate: 'TODO',
        type: 'item',
        icon: 'check_box',
        url: 'apps/todo',
        badge: {
          title: 3,
          bg: 'rgb(255, 111, 0)',
          fg: '#FFFFFF',
        },
      },
      {
        id: 'file-manager',
        title: 'File Manager',
        translate: 'FILE_MANAGER',
        type: 'item',
        icon: 'folder',
        url: 'apps/file-manager',
      },
      {
        id: 'contacts',
        title: 'Contacts',
        translate: 'CONTACTS',
        type: 'item',
        icon: 'account_box',
        url: 'apps/contacts',
      },
      {
        id: 'tasks',
        title: 'Tasks',
        translate: 'TASKS',
        type: 'item',
        icon: 'account_box',
        url: 'apps/tasks',
      },
      {
        id: 'chat',
        title: 'Chat',
        translate: 'CHAT',
        type: 'item',
        icon: 'chat',
        url: 'apps/chat',
        badge: {
          title: 13,
          bg: 'rgb(9, 210, 97)',
          fg: '#FFFFFF',
        },
      },
      {
        id: 'scrumboard',
        title: 'Scrumboard',
        translate: 'SCRUMBOARD',
        type: 'item',
        icon: 'assessment',
        url: 'apps/scrumboard',
      },
      {
        id: 'notes',
        title: 'Notes',
        translate: 'NOTES',
        type: 'item',
        icon: 'note',
        url: 'apps/notes',
      },
    ],
  },
  {
    id: 'pages2',
    title: 'Pages',
    type: 'group',
    icon: 'pages',
    children: [
      {
        id: 'authentication',
        title: 'Authentication',
        type: 'collapse',
        icon: 'lock',
        badge: {
          title: 10,
          bg: '#525E8A',
          fg: '#FFFFFF',
        },
        children: [
          {
            id: 'authentication-login',
            title: 'Login',
            type: 'item',
            url: 'pages/auth/login',
          },
          {
            id: 'login-v2',
            title: 'Login v2',
            type: 'item',
            url: 'pages/auth/login-2',
          },
          {
            id: 'login-v3',
            title: 'Login v3',
            type: 'item',
            url: 'pages/auth/login-3',
          },
          {
            id: 'authentication-register',
            title: 'Register',
            type: 'item',
            url: 'pages/auth/register',
          },
          {
            id: 'authentication-register-v2',
            title: 'Register v2',
            type: 'item',
            url: 'pages/auth/register-2',
          },
          {
            id: 'authentication-register-v3',
            title: 'Register v3',
            type: 'item',
            url: 'pages/auth/register-3',
          },
          {
            id: 'authentication-forgot-password',
            title: 'Forgot Password',
            type: 'item',
            url: 'pages/auth/forgot-password',
          },
          {
            id: 'authentication-forgot-password-v2',
            title: 'Forgot Password v2',
            type: 'item',
            url: 'pages/auth/forgot-password-2',
          },
          {
            id: 'authentication-reset-password',
            title: 'Reset Password',
            type: 'item',
            url: 'pages/auth/reset-password',
          },
          {
            id: 'authentication-reset-password-v2',
            title: 'Reset Password v2',
            type: 'item',
            url: 'pages/auth/reset-password-2',
          },
          {
            id: 'authentication-lock-screen',
            title: 'Lock Screen',
            type: 'item',
            url: 'pages/auth/lock',
          },
          {
            id: 'authentication-mail-confirmation',
            title: 'Mail Confirmation',
            type: 'item',
            url: 'pages/auth/mail-confirm',
          },
        ],
      },
      {
        id: 'coming-soon',
        title: 'Coming Soon',
        type: 'item',
        icon: 'alarm',
        url: 'pages/coming-soon',
      },
      {
        id: 'errors',
        title: 'Errors',
        type: 'collapse',
        icon: 'info',
        children: [
          {
            id: '404',
            title: '404',
            type: 'item',
            url: 'pages/error/error-404',
          },
          {
            id: '500',
            title: '500',
            type: 'item',
            url: 'pages/error/error-500',
          },
        ],
      },
      {
        id: 'invoice',
        title: 'Invoice',
        type: 'collapse',
        icon: 'receipt',
        children: [
          {
            id: 'modern',
            title: 'Modern',
            type: 'item',
            url: 'pages/invoices/modern',
          },
          {
            id: 'compact',
            title: 'Compact',
            type: 'item',
            url: 'pages/invoices/compact',
          },
        ],
      },
      {
        id: 'maintenance',
        title: 'Maintenance',
        type: 'item',
        icon: 'build',
        url: 'pages/maintenance',
      },
      {
        id: 'pricing',
        title: 'Pricing',
        type: 'collapse',
        icon: 'attach_money',
        children: [
          {
            id: 'style-1',
            title: 'Style 1',
            type: 'item',
            url: 'pages/pricing/style-1',
          },
          {
            id: 'style-2',
            title: 'Style 2',
            type: 'item',
            url: 'pages/pricing/style-2',
          },
          {
            id: 'style-3',
            title: 'Style 3',
            type: 'item',
            url: 'pages/pricing/style-3',
          },
        ],
      },
      {
        id: 'profile',
        title: 'Profile',
        type: 'item',
        icon: 'person',
        url: 'pages/profile',
      },
      {
        id: 'search',
        title: 'Search',
        type: 'collapse',
        icon: 'search',
        children: [
          {
            id: 'classic-search',
            title: 'Classic Search',
            type: 'item',
            url: 'pages/search/classic',
          },
          {
            id: 'modern-search',
            title: 'Modern Search',
            type: 'item',
            url: 'pages/search/modern',
          },
        ],
      },
      {
        id: 'faq',
        title: 'Faq',
        type: 'item',
        icon: 'help_outline',
        url: 'pages/faq',
      },
      {
        id: 'knowledge-base',
        title: 'Knowledge Base',
        type: 'item',
        icon: 'import_contacts',
        url: 'pages/knowledge-base',
      },
    ],
  },
  {
    id: 'user-interface2',
    title: 'User Interface',
    type: 'group',
    icon: 'web',
    children: [
      {
        id: 'icons',
        title: 'Icons',
        type: 'item',
        icon: 'photo',
        url: 'ui/icons',
      },
      {
        id: 'ui-typography',
        title: 'Typography',
        type: 'item',
        icon: 'text_fields',
        url: 'ui/typography',
      },
      {
        id: 'helper-classes',
        title: 'Helper Classes',
        type: 'item',
        icon: 'help_outline',
        url: 'ui/helper-classes',
      },
      {
        id: 'page-layouts',
        title: 'Page Layouts',
        type: 'collapse',
        icon: 'view_quilt',
        children: [
          {
            id: 'carded',
            title: 'Carded',
            type: 'collapse',
            badge: {
              title: 12,
              bg: '#525E8A',
              fg: '#FFFFFF',
            },
            children: [
              {
                id: 'carded-full-width',
                title: 'Full Width',
                type: 'item',
                url: 'ui/page-layouts/carded/full-width',
              },
              {
                id: 'carded-full-width-tabbed',
                title: 'Full Width Tabbed',
                type: 'item',
                url: 'ui/page-layouts/carded/full-width-tabbed',
              },
              {
                id: 'carded-full-width-2',
                title: 'Full Width 2',
                type: 'item',
                url: 'ui/page-layouts/carded/full-width-2',
              },
              {
                id: 'carded-full-width-2-tabbed',
                title: 'Full Width 2 Tabbed',
                type: 'item',
                url: 'ui/page-layouts/carded/full-width-2-tabbed',
              },
              {
                id: 'carded-left-sidebar',
                title: 'Left Sidebar',
                type: 'item',
                url: 'ui/page-layouts/carded/left-sidebar',
              },
              {
                id: 'carded-left-sidebar-tabbed',
                title: 'Left Sidebar Tabbed',
                type: 'item',
                url: 'ui/page-layouts/carded/left-sidebar-tabbed',
              },
              {
                id: 'carded-left-sidebar-2',
                title: 'Left Sidebar 2',
                type: 'item',
                url: 'ui/page-layouts/carded/left-sidebar-2',
              },
              {
                id: 'carded-left-sidebar-2-tabbed',
                title: 'Left Sidebar 2 Tabbed',
                type: 'item',
                url: 'ui/page-layouts/carded/left-sidebar-2-tabbed',
              },
              {
                id: 'carded-right-sidebar',
                title: 'Right Sidebar',
                type: 'item',
                url: 'ui/page-layouts/carded/right-sidebar',
              },
              {
                id: 'carded-right-sidebar-tabbed',
                title: 'Right Sidebar Tabbed',
                type: 'item',
                url: 'ui/page-layouts/carded/right-sidebar-tabbed',
              },
              {
                id: 'carded-right-sidebar-2',
                title: 'Right Sidebar 2',
                type: 'item',
                url: 'ui/page-layouts/carded/right-sidebar-2',
              },
              {
                id: 'carded-right-sidebar-2-tabbed',
                title: 'Right Sidebar 2 Tabbed',
                type: 'item',
                url: 'ui/page-layouts/carded/right-sidebar-2-tabbed',
              },
            ],
          },
          {
            id: 'simple',
            title: 'Simple',
            type: 'collapse',
            badge: {
              title: 8,
              bg: '#525E8A',
              fg: '#FFFFFF',
            },
            children: [
              {
                id: 'simple-full-width',
                title: 'Full Width',
                type: 'item',
                url: 'ui/page-layouts/simple/full-width',
              },
              {
                id: 'simple-left-sidebar',
                title: 'Left Sidebar',
                type: 'item',
                url: 'ui/page-layouts/simple/left-sidebar',
              },
              {
                id: 'simple-left-sidebar-2',
                title: 'Left Sidebar 2',
                type: 'item',
                url: 'ui/page-layouts/simple/left-sidebar-2',
              },
              {
                id: 'simple-left-sidebar-3',
                title: 'Left Sidebar 3',
                type: 'item',
                url: 'ui/page-layouts/simple/left-sidebar-3',
              },
              {
                id: 'simple-right-sidebar',
                title: 'Right Sidebar',
                type: 'item',
                url: 'ui/page-layouts/simple/right-sidebar',
              },
              {
                id: 'simple-right-sidebar-2',
                title: 'Right Sidebar 2',
                type: 'item',
                url: 'ui/page-layouts/simple/right-sidebar-2',
              },
              {
                id: 'simple-right-sidebar-3',
                title: 'Right Sidebar 3',
                type: 'item',
                url: 'ui/page-layouts/simple/right-sidebar-3',
              },
              {
                id: 'simple-tabbed',
                title: 'Tabbed',
                type: 'item',
                url: 'ui/page-layouts/simple/tabbed',
              },
            ],
          },
          {
            id: 'blank',
            title: 'Blank',
            type: 'item',
            url: 'ui/page-layouts/blank',
          },
        ],
      },
    ],
  },
  DocumentationNavigation,
  {
    type: 'divider',
    id: 'divider-1',
  },
  {
    id: 'auth',
    title: 'Auth',
    type: 'group',
    icon: 'verified_user',
    children: [
      {
        id: 'login',
        title: 'Login',
        type: 'item',
        url: 'login',
        auth: authRoles.onlyGuest,
        icon: 'lock',
      },
      {
        id: 'register',
        title: 'Register',
        type: 'item',
        url: 'register',
        auth: authRoles.onlyGuest,
        icon: 'person_add',
      },
      {
        id: 'logout',
        title: 'Logout',
        type: 'item',
        auth: authRoles.user,
        url: 'logout',
        icon: 'exit_to_app',
      },
      {
        id: 'auth-admin-example',
        title: 'Admin: Auth protected page',
        type: 'item',
        url: 'auth/admin-role-example',
        icon: 'security',
      },
      {
        id: 'only-admin-navigation-item',
        title: 'Nav item only for Admin',
        type: 'item',
        auth: authRoles.admin,
        url: 'auth/admin-role-example',
        icon: 'verified_user',
      },
      {
        id: 'auth-staff-example',
        title: 'Staff: Auth protected page',
        type: 'item',
        url: 'auth/staff-role-example',
        icon: 'security',
      },
      {
        id: 'only-staff-navigation-item',
        title: 'Nav item only for Staff',
        type: 'item',
        auth: authRoles.staff,
        url: 'auth/staff-role-example',
        icon: 'verified_user',
      },
      {
        id: 'auth-guest-example',
        title: 'Guest: Auth protected page',
        type: 'item',
        url: 'auth/guest-role-example',
        icon: 'security',
      },
      {
        id: 'only-guest-navigation-item',
        title: 'Nav item only for Guest',
        type: 'item',
        auth: authRoles.onlyGuest,
        url: 'auth/guest-role-example',
        icon: 'verified_user',
      },
    ],
  },
  {
    type: 'divider',
    id: 'divider-2',
  },
  {
    id: 'test-group-level-1',
    title: 'Test Group Level 1',
    type: 'group',
    icon: 'clear_all',
    children: [
      {
        id: 'test-item',
        title: 'Test Item',
        type: 'item',
        icon: 'list',
        url: '#',
      },
      {
        id: 'test-link',
        title: 'Test Link',
        type: 'link',
        icon: 'url',
        url: 'http://fusetheme.com',
        target: '_blank',
      },
      {
        id: 'test-collapse-level-1',
        title: 'Test Collapse Level 1',
        type: 'collapse',
        icon: 'dashboard',
        children: [
          {
            id: 'test-item-level-1',
            title: 'Test Item Level 1',
            type: 'item',
            url: '#',
          },
          {
            id: 'test-link-level-1',
            title: 'Test Link Level 1',
            type: 'link',
            url: 'http://fusetheme.com',
            target: '_blank',
          },
          {
            id: 'test-collapse-2',
            title: 'Test Collapse Level 2',
            type: 'collapse',
            children: [
              {
                id: 'test-item-level-2',
                title: 'Test Item Level 2',
                type: 'item',
                url: '#',
              },
              {
                id: 'test-link-level-2',
                title: 'Test Link Level 2',
                type: 'link',
                url: 'http://fusetheme.com',
                target: '_blank',
              },
              {
                id: 'test-collapse-level-3',
                title: 'Test Collapse Level 3',
                type: 'collapse',
                children: [
                  {
                    id: 'test-item-level-3',
                    title: 'Test Item Level 3',
                    type: 'item',
                    url: '#',
                  },
                  {
                    id: 'test-link-level-3',
                    title: 'Test Link Level 3',
                    type: 'link',
                    url: 'http://fusetheme.com',
                    target: '_blank',
                  },
                  {
                    id: 'test-collapse-level-4',
                    title: 'Test Collapse Level 4',
                    type: 'collapse',
                    children: [
                      {
                        id: 'test-item-level-4',
                        title: 'Test Item Level 4',
                        type: 'item',
                        url: '#',
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            id: 'test-group-level-2',
            title: 'Test Group Level 2',
            type: 'group',
            icon: 'apps',
            children: [
              {
                id: 'test-collapse-level-2-2',
                title: 'Test Collapse Level 2',
                type: 'collapse',
                children: [
                  {
                    id: 'test-item-level-2-2',
                    title: 'Test Item Level 2',
                    type: 'item',
                    url: '#',
                  },
                  {
                    id: 'test-link-level-2-2',
                    title: 'Test Link Level 2',
                    type: 'link',
                    url: 'http://fusetheme.com',
                    target: '_blank',
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
];

export default navigationConfig;
